---

- __Author name:__ UBAIDULLAH

- __Email:__ [ai.bussiness.student0@gmail.com](mailto:ai.bussiness.student0@gmail.com)

- __GitHub:__ [github.com/ubaid-X/](https://github.com/ubaid-X/)

- __LinkedIn Profile:__ [linkedin.com/in/ubaid-ullah-634563373/](https://www.linkedin.com/in/ubaid-ullah-634563373/)

- __Kaggle:__ [kaggle.com/ubaidullah01](https://www.kaggle.com/ubaidullah01)

---

> # __Numpy Introduction__

__NumPy__ is a Python library used to handle large sets of numbers efficiently. It provides powerful tools like arrays and mathematical functions that help in doing fast calculations, especially useful in AI, data science, and machine learning.

### `pip install numpy`

In [3]:
# importing numpy library
import numpy as np

# What is Array?

An array is a data structure that stores multiple values of the same type in a single, contiguous block of memory. In NumPy, arrays are called "ndarray" (n-dimensional array) and can hold numbers, strings, or other objects. Arrays allow you to perform mathematical operations efficiently on entire collections of data, making them much faster and more convenient than Python lists for numerical computations.

In [5]:
a = np.arange(10)  # This creates an array with numbers from 0 to 9
print(a)  # Output: [0 1 2 3 4 5 6 7 8 9]

[0 1 2 3 4 5 6 7 8 9]


In [6]:
a.shape  # This will show the shape of the array, which is (10,)

(10,)

- from the above code, when have 1D Array with 10 values

In [ ]:
a2 = a[np.newaxis, :]  # This adds a new axis, converting it to a 2D array
print(a2)  # Output: [[0 1 2 3 4 5 6 7 8 9]]

[[0 1 2 3 4 5 6 7 8 9]]


> Note: __(rows, columns)__ => Shape

In [8]:
a2.shape  # Output: (1, 10), indicating it's a 2D array with 1 row and 10 columns

(1, 10)

- from the above code we can see that a2 has one row and ten columns

In [9]:
a2 = a[:, np.newaxis]  # This adds a new axis, converting it to a 2D array
print(a2)
a2.shape  # This will show the shape of the array, which is (10, 1)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


(10, 1)

- from the above code we can see that a2 has ten rows and one columns

In [10]:
a3 = a2[np.newaxis, :]
print(a3)
a3.shape

[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]
  [6]
  [7]
  [8]
  [9]]]


(1, 10, 1)

> # In Data Science, arrays of different dimensions are used to represent and process various types of data:

- 1D arrays: These are useful for storing simple sequences of data, such as a list of ages, temperatures, or scores. 
    - Example: [23, 45, 67, 89]

- 2D arrays: These are commonly used to represent tabular data, like datasets with rows and columns (similar to spreadsheets or DataFrames).
    - Example: Each row could be a data sample, and each column a feature.

- 3D arrays: These are needed when working with more complex data, such as images (height x width x color channels), time series data (samples x time steps x features), or batches of data for machine learning models.

> # In summary:

 - 1D arrays: Simple lists or vectors.
 - 2D arrays: Tables, matrices, or grayscale images.
 - 3D arrays: Color images, sequences, or batches of data.

### __Choosing the right array dimension helps efficiently store, manipulate, and analyze data in Data Science tasks.__

# Creating Arrays with Numpy

In [ ]:
# 1D Array
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
print(type(a)) # gives the type of the object(array) itself
print(a.dtype) # => checking for data type of array elements
a.shape


[1 2 3 4 5 6]
<class 'numpy.ndarray'>
int64


(6,)

In [22]:
# 2D Array
b = np.array([(1, 2, 3, 4, 5), (6, 7, 8, 9,10)])
print(b)
print(b.dtype)
b.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
int64


(2, 5)

# initialize arrays with python

In [24]:
zeros = np.zeros((4, 7))  # (rows, columns)
print(zeros.dtype)
zeros

float64


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [23]:
ones = np.ones((4, 6))
print(ones.dtype)
ones

float64


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [25]:
full = np.full((3, 7), 5) # => for desireble values like we used 5
print(full.dtype)
full

int64


array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [26]:
full = np.full((3, 7), 2.2) # => for desireble values like we used 2.2
print(full.dtype)
full

float64


array([[2.2, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2]])

In [29]:
# creating identity matrix
identity = np.eye(5)
print(type(identity))
print(identity.dtype)
identity

<class 'numpy.ndarray'>
float64


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Array Attributes

In [ ]:
print(a.shape) # shape of the array => (rows, columns) 
b.shape

(6,)


(2, 5)

In [ ]:
print(len(a)) # length of array
len(b)

6


2

In [40]:
print(a.size) # number of elements in the array
print(b.size)

6
10


In [ ]:
print(a.ndim) # it will give the dimension of the array
print(b.ndim)
print(identity.ndim)

1


2

# Basic Operations

In [44]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [46]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [54]:
g = a - b   # subtraction
g

array([[ 0,  0,  0,  0,  0],
       [-5, -5, -5, -5, -5]])

In [55]:
# 1st method
h = a + b # Addition
h

array([[ 2,  4,  6,  8, 10],
       [ 7,  9, 11, 13, 15]])

In [51]:
# 2nd mthod
h1 = np.add(a, b)
h1

array([[ 2,  4,  6,  8, 10],
       [ 7,  9, 11, 13, 15]])

In [52]:
# multiplication
i = a * b
i

array([[ 1,  4,  9, 16, 25],
       [ 6, 14, 24, 36, 50]])

In [53]:
# Division
j = a / b
j

array([[1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ]])

In [56]:
a

array([1, 2, 3, 4, 5])

In [58]:
# Taking square of each element in a array
k = a ** 2
k

array([ 1,  4,  9, 16, 25])