---

- __Author name:__ UBAIDULLAH

- __Email:__ [ai.bussiness.student0@gmail.com](mailto:ai.bussiness.student0@gmail.com)

- __GitHub:__ [github.com/ubaid-X/](https://github.com/ubaid-X/)

- __LinkedIn Profile:__ [linkedin.com/in/ubaid-ullah-634563373/](https://www.linkedin.com/in/ubaid-ullah-634563373/)

- __Kaggle:__ [kaggle.com/ubaidullah01](https://www.kaggle.com/ubaidullah01)

---

> # __Numpy (Part-2)__

### __Empty Array__

In NumPy, an empty array is an array that is created without initializing its values. It allocates memory for the array but doesn't fill it with specific numbers—so it may contain random or garbage values.

---

Syntax:
python
import numpy as np
arr = np.empty((2, 3))

This creates a 2x3 array where the values are uninitialized.

---

Output Example (random values):
python
array([[1.0302365e-312, 2.1432158e-312, 0.0000000e+000],
       [6.2304207e-307, 1.3796130e-306, 0.0000000e+000]])


---
✅ Use Case:
Use np.empty() when:
- You're going to fill the array immediately after creation.
- You want to optimize performance by skipping initialization.

---
*np.empty() vs np.zeros() in NumPy*

| Feature            | np.empty()                                | np.zeros()                                |
|--------------------|----------------------------------------------|----------------------------------------------|
| What it does   | Creates an array without filling values | Creates an array filled with 0s          |
| Speed          | Faster (no initialization)                  | Slightly slower (fills with 0s)              |
| Values inside  | Garbage/random values                   | All elements are 0                       |
| Use when       | You will overwrite all values anyway    | You need a clean/empty array of 0s       |
| Risk           | Risk of using uninitialized data            | Safe to use immediately                      |

---
🧠 When to Use Each?

- Use *np.empty()* if you're going to fill the array right after creating it. Saves time.
- Use *np.zeros()* when you want to be safe and start with known values.

👀 Summary:

- np.empty(): Fast, but you must fill it yourself.
- np.zeros(): Safe and clean, but a little slower.

---

> ### __Example__

In [2]:
import numpy as np

In [5]:
empty = np.empty((2))
print(empty)
print("----------------------")
print(empty[0])

[0. 0.]
----------------------
0.0


In [9]:
empty = np.empty([2, 3])
print(empty)
print("-----------------")
print(empty[0, 0])


[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [3.22649121e-307 2.67020271e-306 2.42092166e-322]]
-----------------
6.230420704259778e-307


In [10]:
# ascending range from 0 to 5
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [12]:
# np.arange(start, stop, step)
even = np.arange(0, 11, 2) # even numbers from 0 to 10
print(even)

[ 0  2  4  6  8 10]


In [ ]:
# defference(1.5) between each number from 2 to 15
z = np.arange(2, 15, 1.5)
z

array([ 2. ,  3.5,  5. ,  6.5,  8. ,  9.5, 11. , 12.5, 14. ])

---

*What is linspace()?*

`linspace()` is a function in NumPy used to create a linearly spaced list of numbers — like equal steps between two values.

---

Structure (Syntax):
python
numpy.linspace(start, stop, num)


- start → where to begin
- stop → where to end
- num → how many values you want (including start and stop)

---

Example:
python
import numpy as np

arr = np.linspace(0, 10, 5)
print(arr)

**Output:**

[ 0.   2.5  5.   7.5 10. ]


It created 5 numbers evenly spaced from 0 to 10.

---

✅ Real-World Use Cases:

1. Plotting smooth graphs:  
   When plotting a curve, you need smooth x-values — linspace() is perfect.

2. Physics simulations:  
   For example, generating time steps between 0 and 1 second.

3. AI/ML hyperparameter tuning:  
   Testing models with learning rates like from 0.01 to 1.0 in equal steps.

4. Animation frames or video timeline creation.

---

> ### linspace() vs arange()

- *linspace()* → You tell it how many values you want between two numbers.
- *arange()* → You tell it the step size between numbers.

---

In [3]:
# np.linspace() to create an array with values that are spaced linearly ina specified interval is used for line trend
lin = np.linspace(0, 10, num=10)
lin

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [7]:
lin = np.linspace(0, 10, num=1700000)
lin

array([0.00000000e+00, 5.88235640e-06, 1.17647128e-05, ...,
       9.99998824e+00, 9.99999412e+00, 1.00000000e+01], shape=(1700000,))

---
- __you can explicitely specify which data type you want using `dtype` keyword__ 

---

In [11]:
x = np.ones((2, 3), dtype=np.int64) 
print(x)
print("-----------------")
# now checking the dtype of x
print(x.dtype)

[[1 1 1]
 [1 1 1]]
-----------------
int64


> - __int16 vs int32 vs int64 vs int128__

What they are:
They are integer data types with different bit sizes used in programming (like NumPy or AI models) to store numbers.

---

Basic Difference:

| Type     | Bits | Range (Approx.)                       | Memory Used |
|----------|------|----------------------------------------|--------------|
| int16 | 16   | -32,768 to +32,767                    | 2 Bytes      |
| int32 | 32   | -2.1 Billion to +2.1 Billion           | 4 Bytes      |
| int64 | 64   | -9 Quintillion to +9 Quintillion       | 8 Bytes      |
| int128| 128  | Extremely large range (not always supported) | 16 Bytes     |

---
Basic Difference:

| Type     | Bits | Range (Approx.)                       | Memory Used |
|----------|------|----------------------------------------|--------------|
| int16 | 16   | -32,768 to +32,767                    | 2 Bytes      |
| int32 | 32   | -2.1 Billion to +2.1 Billion           | 4 Bytes      |
| int64 | 64   | -9 Quintillion to +9 Quintillion       | 8 Bytes      |
| int128| 128  | Extremely large range (not always supported) | 16 Bytes     |

---

Why use different types?
- int16: Saves memory, but holds smaller numbers → e.g., pixel values in images.
- int32: Default for most AI tasks, balances range and size.
- int64: For big numbers like timestamps or large IDs.
- int128: Rarely used. Mostly in scientific or crypto applications.

---

Real-World AI Use Case:
- Image AI: Uses int8 or int16 for speed/memory.
- Model IDs, timestamps: int64
- Though int128 isn't widely supported in standard NumPy or most hardware, it can be used in:
  1. Cryptography: Handling very large prime numbers and keys.
  2. Blockchain: Calculating balances or hashes with massive integer precision.
  3. Scientific Computing: Extremely large integer values in simulations.
  4. Custom High-Precision Libraries: Where exact integer math is crucial.

> Note: Most CPUs and GPUs don't natively support int128, so it's emulated in software and is slower.


- Deep learning weights or computations: often float32/64, but intermediate steps may use int types.

--- 
- __Sorting array__
---

In [18]:
arr = np.array([20, 1, 100, 2, 4], dtype=np.int64)
arr

array([ 20,   1, 100,   2,   4])

In [20]:
# now sorting the array + storing into original array
arr = np.sort(arr)
arr

array([  1,   2,   4,  20, 100])

> __Different methods of sorting__

---

✳ 1. np.argsort()
→ Returns indices that would sort the array.

📘 Syntax:
python
np.argsort(array, axis=-1)


---

🧪 1D Example – Pakistani Marks List
python
```
import numpy as np
marks = np.array([88, 45, 75, 90])
print(np.argsort(marks))
```

Output:

[1 2 0 3]

🧠 Use Case: Rank students from lowest to highest.

---

🧪 2D Example – City-wise Scores
python
```
scores = np.array([[45, 88], [90, 75]])
print(np.argsort(scores, axis=1))  # Sort each row
```

Output:

[[0 1]
 [1 0]]


---

🧪 3D Example – Exam marks across cities
python
```
data = np.array([
  [[5, 9], [2, 4]],
  [[8, 1], [6, 3]]
])
print(np.argsort(data, axis=2))
```

Output:

[[[0 1]
  [0 1]]

 [[1 0]
  [1 0]]]


---

✳ 2. np.lexsort()
→ Sorts using multiple keys (like Excel: sort by name, then marks).

📘 Syntax:
python
np.lexsort((key2, key1))


---

🧪 1D Example – Sort by City then Age
python
```
cities = np.array(['Lahore', 'Karachi', 'Lahore', 'Islamabad'])
ages = np.array([25, 30, 20, 22])
print(np.lexsort((ages, cities)))
```

---
Output:

[3 1 2 0]


🧠 Use Case: Sort students by city name, then age.

---

🧪 2D/3D: Works only with 1D key arrays. For complex sorting, flatten data.

---

✳ 3. np.searchsorted()
→ Find where to insert a number in a sorted array.

📘 Syntax:
python
np.searchsorted(sorted_array, value)


---

🧪 1D Example – Sorted Donations
python
```
donations = np.array([100, 200, 300])
print(np.searchsorted(donations, 250))
```

Output:

2


---

🧪 2D & 3D:
Not supported directly — flatten or loop required.

---

✳ 4. np.partition()
*→ Rearranges array so smallest k elements come first (not sorted).*

📘 Syntax:
python
np.partition(array, kth)


---

🧪 1D Example – Cricket Scores
python
```
scores = np.array([60, 30, 90, 10])
print(np.partition(scores, 2))
```

Output:

[30 10 60 90]  # Any order, but 2 smallest first


---

🧪 2D Example
python
```
scores = np.array([[60, 10], [90, 30]])
print(np.partition(scores, 1, axis=1))
```

Output:

[[10 60]
 [30 90]]


---

🧪 3D Example
python
```
data = np.array([
  [[5, 3], [7, 1]],
  [[4, 6], [2, 8]]
])
print(np.partition(data, 1, axis=2))
```

Output:

[[[3 5]
  [1 7]]

 [[4 6]
  [2 8]]]


---

✅ Summary Table
| Function        | Purpose                          | Works on | Key Use Case                        |
|----------------|----------------------------------|----------|-------------------------------------|
| argsort()     | Return sort indices              | 1D–3D   | Ranking marks or salaries           |
| lexsort()     | Sort by multiple keys            | 1D keys | Sort by city then age               |
| searchsorted()| Insert index in sorted array     | 1D only | Insert in sorted donations          |
| partition()   | Quick split of small/big values  | 1D–3D   | Top-N cricket scores or salaries    |

---

---
- __Concatenation__
---

In [2]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

In [ ]:
# concatenating the above 1D arrays
c = np.concatenate((a, b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

---
- __we can concatecate 2D array__ 
---

In [ ]:
x = np.array([[1, 2], [3, 4]]) # 2x2 Array
y = np.array([[5, 6]])   # 1x2 Array


In [ ]:
# concatenate 2D Arrays
z = np.concatenate((x, y)) # by default it is row-wise=> axis=0
z

array([[1, 2],
       [3, 4],
       [5, 6]])

### __we can concatenate on both row-wise(top-bottom) and column-wise(left-right)__ ###

>  __1. row-wise(top-bottom)__

In [9]:
z = np.concatenate((x, y), axis=0)
z

array([[1, 2],
       [3, 4],
       [5, 6]])

> __1. column-wise(left-right)__

In [ ]:
x = np.array([[1, 2], [3, 4]]) # 2x2 Array
y = np.array([[5, 6], [7, 8]]) # 2x2 array
z = np.concatenate((x, y), axis=1)
z

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [13]:
# checking dimension of z
z.ndim

2

---
- __Creating 3D Array__

you will need `Two(2) or more 2D Array ` to create a __3D Array__

---

In [ ]:
# creating 3D array
x = np.array([[[2, 3, 4],
               [1, 4, 1]],
              
              [[6, 7, 5],
               [9, 10, 9]]])
print(f"{x.ndim}D")
print("-----------")
print(x)

3D
-----------
[[[ 2  3  4]
  [ 1  4  1]]

 [[ 6  7  5]
  [ 9 10  9]]]


In [29]:
# creating 2nd 3D Array
x = np.array([[[1, 2, 3]],
             [[6, 7, 9]],
             [[4, 5, 8]]])
print(f"Dimention: {x.ndim}D")  # 3D
print(f"shape:{x.shape}")  # (layers/depth, rows, columns)

Dimention: 3D
shape:(3, 1, 3)


In [ ]:
# creating 3rd 3D array
x = np.array([[[2, 3, 4, 11, 34],
               [1, 4, 1, 22, 48]],
              
              [[6, 7, 5, 33, 56],
               [9, 10, 9, 44, 74]],
              
              [[1, 9, 4, 10, 22], 
               [2, 8, 5, 3, 2]]])

print(x)

[[[ 2  3  4 11 34]
  [ 1  4  1 22 48]]

 [[ 6  7  5 33 56]
  [ 9 10  9 44 74]]

 [[ 1  9  4 10 22]
  [ 2  8  5  3  2]]]


In [24]:
print(f"Dimention: {x.ndim}D")  # 3D

Dimention: 3D


In [25]:
print(f"length: {len(x)}") # here length = layers or depth

length: 3


In [27]:
print(f"Total values: {x.size}") # total values in 3D array

Total values: 30


In [28]:
print(f"shape:{x.shape}")  # (layers/depth, rows, columns)


shape:(3, 2, 5)


---
- __Reshaping Array__

when reshaping an array so we have to find their shape like `(3,1,3)` => multiplication of this shape is `9` so while reshaping an array we have to ensure that the multiplication of shape of  new array same as the old

__Example__
old array shape:(3, 1, 3) => 3 * 1 * 3 => 9

new array shape(3, 3) => 3 * 3 => 9

---

In [44]:
a = np.array([[[1, 2, 3, 4]],
             [[6, 7, 9, 5]],
             [[4, 5, 8, 5]]])
print(a.shape)

(3, 1, 4)


In [46]:
# now reshaping the array
a2 = a.reshape(6, 2)
a2.shape

(6, 2)

In [48]:
# before reshaping 
a

array([[[1, 2, 3, 4]],

       [[6, 7, 9, 5]],

       [[4, 5, 8, 5]]])

In [49]:
# after reshaping
a2

array([[1, 2],
       [3, 4],
       [6, 7],
       [9, 5],
       [4, 5],
       [8, 5]])

In [50]:
# reshaping the a2
a2.reshape(2,3,2)


array([[[1, 2],
        [3, 4],
        [6, 7]],

       [[9, 5],
        [4, 5],
        [8, 5]]])

In [51]:
# now reshaping to the first one
a2.reshape(3, 1, 4)

array([[[1, 2, 3, 4]],

       [[6, 7, 9, 5]],

       [[4, 5, 8, 5]]])

---
- __how to convert a 1D array into a 2D array(how to add a new axis to an array)__

---

In [52]:
# creating 1D Array
a = np.array([1, 3, 5, 4, 2])
a.shape

(5,)

In [55]:
# converting that into 2D array
a2 = a[np.newaxis, :]
print(a2.shape)
print("---------")
print(a2)

(1, 5)
---------
[[1 3 5 4 2]]


In [56]:
a3 = a[:, np.newaxis]
print(a3.shape)
a3

(5, 1)


array([[1],
       [3],
       [5],
       [4],
       [2]])


---

🧠 What is np.expand_dims()?

Think of a NumPy array like a box that holds numbers. Sometimes we want to add an extra layer (dimension) to that box to help with math or machine learning tasks.

👉 np.expand_dims() is like putting your toy in a bigger box. It doesn’t change the toy (data), just gives it more shape.

---

🛠 Syntax

python
np.expand_dims(array, axis)


- array: The data you have (like a list or NumPy array).
- axis: Where you want to add the new box (dimension).  
  - axis=0: Add dimension at the front.
  - axis=1: Add dimension in the middle.

---

🎲 Examples

```python
import numpy as np

Simple 1D array (like a line of numbers)
arr = np.array([1, 2, 3])
print(arr.shape)  # Output: (3,)
```

Example 1: Add a dimension at axis=0
```python
expanded = np.expand_dims(arr, axis=0)
print(expanded.shape)  # Output: (1, 3)
```

🔍 Now it's like:

[[1, 2, 3]]


Example 2: Add a dimension at axis=1
```python
expanded = np.expand_dims(arr, axis=1)
print(expanded.shape)  # Output: (3, 1)
```

🔍 Now it's like:

[[1],
 [2],
 [3]]


---

🌍 Real-World Use Cases

- 🤖 In machine learning, models often need inputs in 2D or 3D shape.
- 📸 In image processing, images may need an extra "channel" dimension.
- 📈 When preparing data for batch processing or feeding into deep learning models.

---

🎓 Tip: Use np.expand_dims() when your array is too flat and your model or function says “I need more shape!” 😄

---


---
- __using np.nonzero()__

we can use it to print the indices of elements with condition

---