---

- __Author name:__ UBAIDULLAH

- __Email:__ [ai.bussiness.student0@gmail.com](mailto:ai.bussiness.student0@gmail.com)

- __GitHub:__ [github.com/ubaid-X/](https://github.com/ubaid-X/)

- __LinkedIn Profile:__ [linkedin.com/in/ubaid-ullah-634563373/](https://www.linkedin.com/in/ubaid-ullah-634563373/)

- __Kaggle:__ [kaggle.com/ubaidullah01](https://www.kaggle.com/ubaidullah01)

---

---
> # __Creating Matrices__

you can pass python lists of lists to create 2D array(`"Matrix"`)to represent them in numpy

In [48]:
import numpy as np

In [49]:
# creating 2x3(rows, columns) matrix
a = np.array([[1, 2, 3], [4, 5,  6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
# creating a matrix of big dimension
b = np.arange(0, 100, 2).reshape(5, 10)
print(b) 

[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]


In [51]:
# slicing a matrix
b[1:3, 3:5]

array([[26, 28],
       [46, 48]])

In [52]:
# slicing a matrix
b[0:, 3:5]

array([[ 6,  8],
       [26, 28],
       [46, 48],
       [66, 68],
       [86, 88]])

### __Explaination__

syntax: `b[range of rows, range of columns]`

`b[0:3, 3:5]` meaning:

take three rows of (`0, 1, 2`) indexes and take columns of (`3, 4`) index

In [53]:
# it will give all matrix
b[:, :]

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [54]:
b[0:3, 0] #taking two rows and column

array([ 0, 20, 40])

In [55]:
b[1, 3:5]  # taking one row and two columns

array([26, 28])

In [56]:
b[0:3] # taking three rows and all columns

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58]])

In [57]:
b[1] # taking one rows and all values of it(column)

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [58]:
# creating another matrix from existing
c = b[0:3, 3:6]
c

array([[ 6,  8, 10],
       [26, 28, 30],
       [46, 48, 50]])

---
- __Aggregate matrices the same way as we aggregated vectors__

In [59]:
# maximum value in c matrix
c.max()

np.int64(50)

In [60]:
# row which have max count of values
c.max(axis=0)

array([46, 48, 50])

In [61]:
# column which have max count of values
c.max(axis=1)

array([10, 30, 50])

---

In [62]:
# minimum value in c matrix
c.min()

np.int64(6)

In [63]:
# row which have min count of values
c.min(axis=0)

array([ 6,  8, 10])

In [64]:
# column which have min count of values
c.min(axis=1)

array([ 6, 26, 46])

---

In [65]:
# sum of all values in c matrix
c.sum()

np.int64(252)

---

In [66]:
# mean of all values in c matrix
c.mean()

np.float64(28.0)

---

In [67]:
d = np.arange(0, 20, 2).reshape(5, 2)
d

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [68]:
# add this values rows wise with every row, we can also do operations like  *,-,/ etc
d + np.array([10, 5])

array([[10,  7],
       [14, 11],
       [18, 15],
       [22, 19],
       [26, 23]])

In [69]:
# multiplication
d * np.array([10, 5])

array([[  0,  10],
       [ 40,  30],
       [ 80,  50],
       [120,  70],
       [160,  90]])

In [70]:
# adding new row
np.vstack((d, np.array([44, 66])))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [44, 66]])

---
- __How to get Unique items and counts__

In [71]:
# it will give unique array from duplicate array
a = np.array([11, 11, 22, 22, 33, 33, 34, 34, 100])
np.unique(a)

array([ 11,  22,  33,  34, 100])

In [72]:
# to get the indeces of unique value in a numpy array
np.unique(a, return_index=True)

(array([ 11,  22,  33,  34, 100]), array([0, 2, 4, 6, 8]))

In [73]:
# frequency count of unique values in numpy array
np.unique(a, return_counts=True)

(array([ 11,  22,  33,  34, 100]), array([2, 2, 2, 2, 1]))

In [74]:
# creating 2D array
e = np.array([[1, 2, 3, 4], [11, 22, 33 ,44], [1, 2, 3, 4], [1, 4, 3, 2]])
e

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44],
       [ 1,  2,  3,  4],
       [ 1,  4,  3,  2]])

In [75]:
# we can also do it on 2D array as same as above
# unique rows
np.unique(e, axis=0)

# we can also do it column-wise (axis=1)

array([[ 1,  2,  3,  4],
       [ 1,  4,  3,  2],
       [11, 22, 33, 44]])

In [76]:
# Transposing an array
e.transpose()

array([[ 1, 11,  1,  1],
       [ 2, 22,  2,  4],
       [ 3, 33,  3,  3],
       [ 4, 44,  4,  2]])

In [77]:
# we can also use .T for transpose
e.T

array([[ 1, 11,  1,  1],
       [ 2, 22,  2,  4],
       [ 3, 33,  3,  3],
       [ 4, 44,  4,  2]])

---
> # __How to reverse an Array__

- __reversing 1D array__

In [78]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [79]:
np.flip(arr)

array([6, 5, 4, 3, 2, 1])

- __reversing 2D array__

In [84]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
np.flip(arr_2d)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [87]:
# reversing only rows in array
np.flip(arr_2d, axis=0)

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [85]:
# reversing only columns
np.flip(arr_2d, axis=1)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

- __we can also reverse the content of one column or one row__

In [90]:
# reversing only first row
np.flip(arr_2d[0])

array([3, 2, 1])

In [91]:
# reversing only first column
np.flip(arr_2d[:, 0])

array([7, 4, 1])

---
> # __Saving and loading files using numpy__

In [95]:
csv_arr = np.array([1, 2, 3, 4, 5])

# Saving the array to a CSV file
np.savetxt('./np dataset/array.csv', csv_arr, delimiter=',')

- __Now loading CSV file__

In [96]:
df = np.loadtxt('./np dataset/array.csv')
df

array([1., 2., 3., 4., 5.])

---
> # __for more you can visit numpy officially documentation__
---

> # __Read the blog__ [click here](https://codanics.com/data-preprocessing-for-data-science/)