---

- __Author name:__ UBAIDULLAH

- __Email:__ [ai.bussiness.student0@gmail.com](mailto:ai.bussiness.student0@gmail.com)

- __GitHub:__ [github.com/ubaid-X/](https://github.com/ubaid-X/)

- __LinkedIn Profile:__ [linkedin.com/in/ubaid-ullah-634563373/](https://www.linkedin.com/in/ubaid-ullah-634563373/)

- __Kaggle:__ [kaggle.com/ubaidullah01](https://www.kaggle.com/ubaidullah01)

---

---
> # __Indexing and slicing__

---

In [1]:
# importing numpy library
import numpy as np

In [2]:
# creating 1D array
data = np.arange(1, 10)
data

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# accessing value on specific index
print(data[0])  # first element
print(data[1])  # second element

1
2


In [4]:
# slicing
data[0:3]  # first three elements

array([1, 2, 3])

In [5]:
data[1:]  # from second element to the end

array([2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
data[:3]  # from start to the third value

array([1, 2, 3])

In [7]:
data[-1]  # last element

np.int64(9)

In [8]:
data[-3:]  # last three elements from the end

array([7, 8, 9])

In [9]:
data[-6:-2] # from -6 to -2 (not including -2)

array([4, 5, 6, 7])

In [10]:
# creating 2D array
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
b[0] # accessing the first row

array([1, 2, 3])

In [12]:
b[0, 1]  # accessing the first row and second column => specific value(point) => 2

np.int64(2)

In [13]:
b[1:, 1:] # accessing all rows from the second row and all columns from the second column

array([[5, 6],
       [8, 9]])

In [14]:
b[b < 5] # accessing all values less than 5

array([1, 2, 3, 4])

In [15]:
b[b % 2 == 0] # accessing all even values in the array

array([2, 4, 6, 8])

In [16]:
b[b % 2 == 1] # accessing all odd values in the array

array([1, 3, 5, 7, 9])

> ## Logical operator in python

---

| 🔢 Operator | 🔧 Python Syntax | 🧠 Explanation | 💻 Example + Output |
|----------------|----------------------|--------------------|-------------------------|
| AND        | and (like &)    | Returns True only if both conditions are true | True and False → False |
| OR         | or (like |)     | Returns True if at least one condition is true | True or False → True |
| NOT        | not (like !)     | Reverses the truth value (True → False) | not True → False |

---

✅ Detailed Example:

python

`a = 5`

`b = 10`

`print(a > 3 and b < 15)`   # True and True → True

`print(a < 3 or b == 10)`   # False or True → True

`print(not (a == 5))`     # not True → False


__Output:__

True 

True   

False


---

In [17]:
# using two conditions
b[(b > 2) & (b < 8)] # accessing all values greater than 2 and less than 8

array([3, 4, 5, 6, 7])

In [18]:
# creating 2D array
a  =np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
# using three conditions
b[(b > 2) & (b < 8) & (b % 2 == 0)] # accessing all even values which are greater than 2 and less than 8

array([4, 6])

In [20]:
b[(b > 2) | (b < 8)] # accessing all values greater than 2 or less than 8

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.nonzero(a > 5)  # using np.nonzero() to get indices of elements greater than 5   

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))