---

- __Author name:__ UBAIDULLAH

- __Email:__ [ai.bussiness.student0@gmail.com](mailto:ai.bussiness.student0@gmail.com)

- __GitHub:__ [github.com/ubaid-X/](https://github.com/ubaid-X/)

- __LinkedIn Profile:__ [linkedin.com/in/ubaid-ullah-634563373/](https://www.linkedin.com/in/ubaid-ullah-634563373/)

- __Kaggle:__ [kaggle.com/ubaidullah01](https://www.kaggle.com/ubaidullah01)

---

---
> # __How to create an array from existing data__
---


In [1]:
import numpy as np

In [ ]:
# creating an array
a = np.arange(0, 500, 7)
a

array([  0,   7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84,
        91,  98, 105, 112, 119, 126, 133, 140, 147, 154, 161, 168, 175,
       182, 189, 196, 203, 210, 217, 224, 231, 238, 245, 252, 259, 266,
       273, 280, 287, 294, 301, 308, 315, 322, 329, 336, 343, 350, 357,
       364, 371, 378, 385, 392, 399, 406, 413, 420, 427, 434, 441, 448,
       455, 462, 469, 476, 483, 490, 497])

In [4]:
len(a)

72

In [5]:
# creating array from existing data
arr1 = a[39:43]
arr1

array([273, 280, 287, 294])

---
- __we can stack two or more existing arrays, both vertically and horizontally using `vstack()` and `hstack()`__
  - we can also do it using concatenate method which we learned previous lectures
---

In [6]:
# creating arrays
a1 = np.array([[1, 2 , 3], 
               [7, 8, 9]])

a2 = np.array([[4, 5, 6],
              [11, 13, 17]])

In [7]:
print(a1)
print("---------")
print(a2)

[[1 2 3]
 [7 8 9]]
---------
[[ 4  5  6]
 [11 13 17]]


In [11]:
# Now stacking vertically 
b = np.vstack((a1, a2))
b

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [11, 13, 17]])

In [13]:
# Now stacking horizontally
c = np.hstack((a1, a2))
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 11, 13, 17]])